# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15w48LmndWV1nmYbTOdlDyb7nnGJguZYP
"""

import streamlit as st

# Title
st.set_page_config(page_title="Team Attendance", layout="centered")
st.title("🔆 Team Attendance Tracker")

# Define team members
team_members = [
    "Alice", "Bob", "Charlie", "Diana", "Ethan",
    "Fiona", "George", "Hannah", "Ivy", "Jack"
]

# Initialize session state for each member
for member in team_members:
    if member not in st.session_state:
        st.session_state[member] = False

# Neon-style CSS
st.markdown("""
    <style>
    .neon-on {
        background-color: #39ff14;
        color: black;
        font-weight: bold;
        border-radius: 10px;
        padding: 10px 20px;
        text-align: center;
        box-shadow: 0 0 10px #39ff14, 0 0 20px #39ff14, 0 0 30px #39ff14;
    }
    .neon-off {
        background-color: #222;
        color: white;
        border: 1px solid #444;
        border-radius: 10px;
        padding: 10px 20px;
        text-align: center;
    }
    button[title~="Toggle"] {
        border: none;
        background: none;
        padding: 0;
    }
    </style>
""", unsafe_allow_html=True)

# Display toggle buttons
cols = st.columns(2)
for idx, member in enumerate(team_members):
    with cols[idx % 2]:
        # Show as clickable button
        if st.button(f"{'✅ ' if st.session_state[member] else '❌ '}{member}", key=member):
            st.session_state[member] = not st.session_state[member]

        # Display current state in neon style
        status_class = "neon-on" if st.session_state[member] else "neon-off"
        status_text = "ON" if st.session_state[member] else "OFF"
        st.markdown(f'<div class="{status_class}">{member} is {status_text}</div>', unsafe_allow_html=True)